In [48]:
# Importing the necesary libraries that we are going to work with.

import pandas as pd
import yaml
from riotwatcher import LolWatcher, ApiError
from datetime import date
import time

In [19]:
config = yaml.load(open("riot-config.yaml"), Loader=yaml.FullLoader) # Reading in the riot-config.yaml file

lol_watcher = LolWatcher(config['API']) # Riot API Key

region = 'eun1' # Defining the region of the accounts scrape

players = [ 'xzxxsx', 'xRazvYx', 'BalonulDeAur', 'Syrebral', 'Rin Hen Tie', 'PeleBogdan', 'Damondar', 'Hit the Flash', 'MrSkit']

player_info = lol_watcher.summoner.by_name(region, 'xzxxsx') # Get player's info by their IGN. 

player_ranked_stats = lol_watcher.league.by_summoner(region, player_info['id']) # Get player's ranked stats.

player_matches = lol_watcher.match.matchlist_by_account(region, player_info['accountId']) # Get player's match history. Limited to last 100 records.

champ_list = lol_watcher.data_dragon.champions("10.15.1", False, 'en_US')['data'] # Get all available info about an in-game champion.


# For Riot's API, the 404 status code indicates that the requested data wasn't found and
# should be expected to occur in normal operation, as in the case of a an
# invalid summoner name, match ID, etc.
#
# The 429 status code indicates that the user has sent too many requests
# in a given amount of time ("rate limiting").

# Custom Error:
# try:
#     response = lol_watcher.summoner.by_name(region, 'this_is_probably_not_anyones_summoner_name')
# except ApiError as err:
#     if err.response.status_code == 429:
#         print('We should retry in {} seconds.'.format(err.response.headers['Retry-After']))
#         print('this retry-after is handled by default by the RiotWatcher library')
#         print('future requests wait until the retry-after time passes')
#     elif err.response.status_code == 404:
#         print('Summoner with that ridiculous name not found.')
#     else:
#         raise

In [5]:
# fetch match details
last_match = player_matches['matches'][0]
match_detail = lol_watcher.match.by_id(region, last_match['gameId'])
participants = []
for row in match_detail['participants']:
    participants_row = {}
    participants_row['gameID'] = last_match['gameId']
    participants_row['champion'] = row['championId']
    participants_row['spell1'] = row['spell1Id']
    participants_row['spell2'] = row['spell2Id']
    participants_row['win'] = row['stats']['win']
    participants_row['kills'] = row['stats']['kills']
    participants_row['deaths'] = row['stats']['deaths']
    participants_row['assists'] = row['stats']['assists']
    participants_row['totalDamageDealt'] = row['stats']['totalDamageDealt']
    participants_row['goldEarned'] = row['stats']['goldEarned']
    participants_row['champLevel'] = row['stats']['champLevel']
    participants_row['totalMinionsKilled'] = row['stats']['totalMinionsKilled']
    participants_row['item0'] = row['stats']['item0']
    participants_row['item1'] = row['stats']['item1']
    participants.append(participants_row)
df = pd.DataFrame(participants)

In [76]:
# check league's latest version
# latest = lol_watcher.data_dragon.versions_for_region(my_region)['n']['champion']
# Lets get some champions static information
# static_champ_list = lol_watcher.data_dragon.champions("10.15.1", False, 'en_US')
# champ static list data to dict for looking up
champ_dict = {}
for key in champ_list:
    row = champ_list[key]
    champ_dict[row['key']] = row['id']
for row in participants:
#     print(str(row['champion']) + ' ' + champ_dict[str(row['champion'])])
    row['championName'] = champ_dict[str(row['champion'])]
# print dataframe
df = pd.DataFrame(participants)

In [20]:
users = {}

import time

for player in players:
    print(player)
    player_data = {}
    
    player_info = lol_watcher.summoner.by_name(region, player)
    
    player_data['name'] = player_info['name']
    player_data['summonerLevel'] = player_info['summonerLevel']
    
    player_matches = lol_watcher.match.matchlist_by_account(region, player_info['accountId'])['matches']
    
    player_data['games'] = []
    
    for match in player_matches:
        if match['queue'] == 440:
            game = {}
            game['gameId'] = match['gameId']
            game['champion'] = match['champion']
            game['timestamp'] = match['timestamp']
            game['role'] = match['role']
            game['lane'] = match['lane']
#             game['duration'] = round(match['gameDuration'] / 60)

            player_data['games'].append(game)
#                     game['win'] = participant['stats']['win']
#                     game['K'] = participant['stats']['kills']
#                     game['D'] = participant['stats']['deaths']
#                     game['A'] = participant['stats']['assists']
#                     game['largestMultiKill'] = participant['stats']['largestMultiKill']
        
    users[player] = player_data

xzxxsx
xRazvYx
BalonulDeAur
Syrebral
Rin Hen Tie
PeleBogdan
Damondar
Hit the Flash
MrSkit

In [25]:
for user in users.keys():
    print(f'Extracting user: {user}')
    
    users[user]['stats'] = []
    
    for match in users[user]['games']:
        users[user]['matches']=[]
        game = {}
        game['gameId'] = match['gameId']
        game['champion'] = match['champion']
        game['timestamp'] = match['timestamp']
        game['role'] = match['role']
        game['lane'] = match['lane']
        
        while True:
            try:
                match_detail = lol_watcher.match.by_id(region, match['gameId'])
                pass
            except:
                time.sleep(1)
                continue
            break
            
        game['duration'] = round(match_detail['gameDuration'] / 60)

        for participant in match_detail['participants']:
            if match['champion'] == participant['championId']:
#                 users[user]['stats'].append(participant['stats'])
                for stat,val in participant['stats'].items():
                    game[stat]=val
            
        users[user]['stats'].append(game)

Extracting user: xzxxsx
Extracting user: xRazvYx
Extracting user: BalonulDeAur
Extracting user: Syrebral
Extracting user: Rin Hen Tie
Extracting user: PeleBogdan
Extracting user: Damondar
Extracting user: Hit the Flash
Extracting user: MrSkit

In [75]:
df = pd.DataFrame(users['xRazvYx']['stats'])

def map_champ(row):
    return champ_dict[str(row)]

df['champion']= df['champion'].apply(map_champ)

df['minionsKilled'] = sum([df['totalMinionsKilled'],df['neutralMinionsKilled'],df['neutralMinionsKilledTeamJungle'],df['neutralMinionsKilledEnemyJungle']])

cols = ['gameId',
 'champion',
 'timestamp',
 'role',
 'lane',
 'duration',
 'participantId',
 'win',
 'kills',
 'deaths',
 'assists',
 'largestKillingSpree',
 'largestMultiKill',
 'killingSprees',
 'longestTimeSpentLiving',
 'doubleKills',
 'tripleKills',
 'quadraKills',
 'pentaKills',
 'unrealKills',
 'totalDamageDealt',
 'magicDamageDealt',
 'physicalDamageDealt',
 'trueDamageDealt',
 'largestCriticalStrike',
 'totalDamageDealtToChampions',
 'magicDamageDealtToChampions',
 'physicalDamageDealtToChampions',
 'trueDamageDealtToChampions',
 'totalHeal',
 'totalUnitsHealed',
 'damageSelfMitigated',
 'damageDealtToObjectives',
 'damageDealtToTurrets',
 'visionScore',
 'timeCCingOthers',
 'totalDamageTaken',
 'magicalDamageTaken',
 'physicalDamageTaken',
 'trueDamageTaken',
 'goldEarned',
 'goldSpent',
 'turretKills',
 'inhibitorKills',
 'minionsKilled',
 'totalMinionsKilled',
 'neutralMinionsKilled',
 'neutralMinionsKilledTeamJungle',
 'neutralMinionsKilledEnemyJungle',
 'totalTimeCrowdControlDealt',
 'champLevel',
 'visionWardsBoughtInGame',
 'sightWardsBoughtInGame',
 'wardsPlaced',
 'wardsKilled',
 'firstBloodKill',
 'firstBloodAssist',
 'firstTowerKill',
 'firstTowerAssist',
 'firstInhibitorKill',
 'firstInhibitorAssist',
 'combatPlayerScore',
 'objectivePlayerScore',
 'totalPlayerScore',
 'totalScoreRank']

df.loc[:,cols]

,gameId,champion,timestamp,role,lane,duration,participantId,win,kills,deaths,...,firstBloodKill,firstBloodAssist,firstTowerKill,firstTowerAssist,firstInhibitorKill,firstInhibitorAssist,combatPlayerScore,objectivePlayerScore,totalPlayerScore,totalScoreRank
0,2544756867,Zed,1595966769879,SOLO,MID,41,7,True,11,6,...,False,False,False,False,False,True,0,0,0,0
1,2543774811,Ekko,1595873672260,SOLO,MID,29,7,False,1,8,...,False,False,False,False,False,False,0,0,0,0
2,2543038823,Rengar,1595797609783,NONE,JUNGLE,43,4,True,13,14,...,False,False,False,False,False,False,0,0,0,0
3,2542786996,Vayne,1595783479045,SOLO,TOP,34,7,False,5,4,...,False,False,False,False,False,False,0,0,0,0
4,2542809961,Shen,1595780078465,SOLO,TOP,31,7,True,5,3,...,False,False,False,False,False,False,0,0,0,0
5,2542119244,Ekko,1595714733231,SOLO,MID,29,6,True,11,6,...,False,False,False,False,True,False,0,0,0,0
6,2542053957,Lissandra,1595711825687,SOLO,MID,37,6,True,7,8,...,False,False,False,False,False,False,0,0,0,0
7,2541158439,Yasuo,1595622230890,SOLO,MID,29,1,True,12,8,...,False,False,False,True,False,True,0,0,0,0
8,2541083730,Lissandra,1595620027095,DUO_SUPPORT,NONE,20,6,True,3,1,...,False,False,False,False,NaN,NaN,0,0,0,0
9,2541087611,Lissandra,1595617234434,SOLO,MID,34,7,True,5,7,...,False,False,False,False,False,True,0,0,0,0
10,2540928969,Riven,1595607343196,SOLO,TOP,24,2,False,2,7,...,False,False,False,False,False,False,0,0,0,0
11,2540238900,DrMundo,1595537153935,SOLO,TOP,31,8,True,5,2,...,False,False,False,False,False,True,0,0,0,0
12,2540182669,DrMundo,1595534713669,DUO_SUPPORT,TOP,30,2,True,1,4,...,False,False,False,False,NaN,NaN,0,0,0,0
13,2540147659,Vladimir,1595532485992,SOLO,TOP,26,7,True,0,4,...,False,False,False,False,False,False,0,0,0,0
14,2540060174,Kayle,1595529132702,SOLO,TOP,30,2,False,3,4,...,False,False,False,False,False,False,0,0,0,0
15,2540006509,Gnar,1595527520324,SOLO,TOP,21,7,True,9,2,...,False,False,True,False,NaN,NaN,0,0,0,0
16,2538478503,Morgana,1595371157600,DUO_SUPPORT,BOTTOM,36,1,False,3,9,...,False,False,False,False,False,False,0,0,0,0
17,2538414611,Nautilus,1595368177200,DUO_SUPPORT,BOTTOM,42,6,True,6,11,...,False,False,False,False,False,True,0,0,0,0
18,2537553520,MonkeyKing,1595275985354,SOLO,TOP,27,2,False,2,6,...,False,False,False,False,False,False,0,0,0,0
19,2536657188,MonkeyKing,1595181739934,SOLO,TOP,37,6,True,5,6,...,False,False,False,False,True,False,0,0,0,0
20,2536029378,Shen,1595111416024,SOLO,TOP,44,2,False,4,9,...,False,False,False,False,False,False,0,0,0,0
21,2536014803,Singed,1595108661379,NONE,JUNGLE,37,7,False,6,9,...,False,False,False,False,False,False,0,0,0,0
22,2536012888,Singed,1595107371182,DUO_SUPPORT,NONE,16,2,False,0,4,...,False,False,False,False,NaN,NaN,0,0,0,0
23,2535998106,Nasus,1595104397359,SOLO,TOP,33,1,False,5,4,...,False,False,False,False,False,False,0,0,0,0
24,2535943059,Yasuo,1595101425358,SOLO,TOP,31,7,True,7,4,...,False,False,False,False,False,True,0,0,0,0
25,2535196366,Vayne,1595020582057,DUO_CARRY,BOTTOM,27,7,False,3,7,...,False,False,False,False,False,False,0,0,0,0
26,2534482754,Morgana,1594938022731,DUO_SUPPORT,BOTTOM,32,6,False,2,13,...,False,False,False,False,False,False,0,0,0,0
27,2533773192,MasterYi,1594855297630,NONE,JUNGLE,22,1,False,1,5,...,False,False,False,False,False,False,0,0,0,0
28,2533810830,Rammus,1594853097388,NONE,JUNGLE,28,1,False,6,11,...,False,False,False,False,False,False,0,0,0,0
29,2497467000,Leona,1591051167114,DUO_SUPPORT,BOTTOM,23,4,False,2,8,...,False,False,False,False,NaN,NaN,0,0,0,0
30,2497512410,Singed,1591048721652,SOLO,TOP,22,9,False,0,9,...,False,False,False,False,False,False,0,0,0,0
31,2455361791,Rammus,1587670356263,DUO_SUPPORT,NONE,17,3,False,0,9,...,False,False,False,False,NaN,NaN,0,0,0,0
32,2455206303,Shyvana,1587668443260,NONE,JUNGLE,24,8,False,5,7,...,True,False,False,False,False,False,0,0,0,0
33,2431147704,Xerath,1585996853560,SOLO,MID,35,8,False,16,11,...,False,False,False,False,False,False,0,0,0,0

In [71]:
df = pd.DataFrame(users['xzxxsx']['stats'])

In [77]:
# list(pd.DataFrame(users['xzxxsx']['stats']).columns)